[general]

import = ["dracula.toml"]
live_config_reload = true

[window]
decorations = "None"
opacity = 1.0

[font]
normal = { family = "JetBrainsMonoNerdFontMono", style = "Regular"}
bold = { family = "JetBrainsMonoNerdFontMono", style = "Bold"}
italic = { family = "JetBrainsMonoNerdFontMono", style = "Italic"}
bold_italic = { family = "JetBrainsMonoNerdFontMono", style = "BoldItalic"}
size = 12
offset = { x = 0, y = 1 }

